server:
  port: 8083

spring:
  profiles:
    active: dev
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    queue: ms.email
logging:
  level:
    com:
      ms:
        email: TRACE

#email-properties
mail:
  host: smtp.gmail.com
  port: 587
  username: kitzgustavo@gmail.com
  password: clftzmwaekcssjks