spring:
  profiles:
    active: dev
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: liquibase/master.xml
    enabled: true
  main:
    allow-bean-definition-overriding: true

# application:
feign:
  client:
    config:
      email-service:
        url: http://localhost:8083